FROM node:24-alpine
WORKDIR /app

# Dependencies
COPY ./backend/website/package.json .
RUN npm install prisma@$(node -pe "require('./package').devDependencies.prisma")

# Schema
COPY ./database/model.prisma ./schema.prisma

# Migration data
COPY ./database/migrations ./migrations

# Perform migration
CMD ["npx", "prisma", "migrate", "deploy"]
